export enum ACTION {
    ALL_EVENTS = 'ALL_EVENTS',
    ALL_MY_EVENTS = 'ALL_MY_EVENTS',
    ALL_JOINED_EVENTS = 'ALL_JOINED_EVENTS',
    CREATE_EVENT = 'CREATE_EVENT',
    EVENT_INFO = 'EVENT_INFO',
    USER_AUTH = 'USER_AUTH',
    JOIN_EVENT = 'JOIN_EVENT',
    JOINED = 'JOINED',
}